apiVersion: v1
kind: Service
metadata:
  name: my-react-app
  labels:
    run: my-react-app
spec:
  type: NodePort
  ports:
  - nodePort: 32410
    protocol: TCP
    port: 4200
    targetPort: 4200
  selector:
    run: my-react-app


